name: Build and Deploy C shared library

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Determine version
      id: determine_version
      run: |
        if [ -n "$GITHUB_REF" ]; then
          export VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
        else
          export VERSION="0.0.0"
        fi
        echo "{version}={$VERSION}" >> $GITHUB_OUTPUT

    - name: Build
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DVERSION=${{ steps.determine_version.outputs.version }} .
        make
      env:
        CC: gcc
        CXX: g++

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.determine_version.outputs.version }}
        release_name: Release ${{ steps.determine_version.outputs.version }}
        body: This is the release of version ${{ steps.determine_version.outputs.version }} of AES shared library.
        draft: false
        prerelease: false

    - name: Upload release asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/
        asset_name: build
        asset_content_type: application/octet-stream
